/** @file

  Platform Configuration C Struct Header File.

  Copyright (c) 2026, Intel Corporation. All rights reserved.<BR>
  SPDX-License-Identifier: BSD-2-Clause-Patent

  This file is automatically generated. Please do NOT modify !!!

**/

#ifndef __FSPT_UPD_H__
#define __FSPT_UPD_H__

#include <FspUpd.h>

#pragma pack(1)

typedef struct {

/** N/A
**/
  UINT64                      MicrocodeRegionBase;

/** N/A
**/
  UINT64                      MicrocodeRegionLength;

/** N/A
**/
  UINT64                      CodeRegionBase;

/** N/A
**/
  UINT64                      CodeRegionLength;

} FSPT_CORE_UPD;


typedef struct {

/**  Disable Port80 output in FSP-T
  0:VPD-Style, 1:Enable Port80 Output[Default], 2:Disable Port80 Output
**/
  UINT8                       FsptPort80RouteDisable;

/** N/A
**/
  UINT8                       ReservedTempRamInitUpd[31];

} FSPT_CONFIG;


typedef struct {

/** N/A
**/
  FSP_UPD_HEADER              FspUpdHeader;

/** N/A
**/
  FSPT_ARCH2_UPD              FsptArchUpd;

/** N/A
**/
  FSPT_CORE_UPD               FsptCoreUpd;

/** N/A
**/
  FSPT_CONFIG                 FsptConfig;

/** N/A
**/
  UINT16                      UpdTerminator;

} FSPT_UPD;

#pragma pack()

#endif
