/** @file

  Platform Configuration C Struct Header File.

  Copyright (c) 2026, Intel Corporation. All rights reserved.<BR>
  SPDX-License-Identifier: BSD-2-Clause-Patent

  This file is automatically generated. Please do NOT modify !!!

**/

#ifndef __FSPUPD_H__
#define __FSPUPD_H__

#include <FspEas.h>

#pragma pack(1)

#define FSPT_UPD_SIGNATURE    0x545F445055524E47  /* 'GNRUPD_T' */

#define FSPM_UPD_SIGNATURE    0x4D5F445055524E47  /* 'GNRUPD_M' */

#define FSPS_UPD_SIGNATURE    0x535F445055524E47  /* 'GNRUPD_S' */

#define FSPI_UPD_SIGNATURE    0x495F445055524E47  /* 'GNRUPD_I' */

#pragma pack()

#endif
