/** @file FspUpd.h

 @copyright
  Copyright (c) 2021, Intel Corporation. All rights reserved.<BR>

  SPDX-License-Identifier: BSD-2-Clause-Patent

  This file is automatically generated. Please do NOT modify !!!

**/

#ifndef __FSPUPD_H__
#define __FSPUPD_H__

#include <FspEas.h>

#pragma pack(1)

#define FSPT_UPD_SIGNATURE               0x545F445055434F53        /* 'SOCUPD_T' */

#define FSPM_UPD_SIGNATURE               0x4D5F445055434F53        /* 'SOCUPD_M' */

#define FSPS_UPD_SIGNATURE               0x535F445055434F53        /* 'SOCUPD_S' */

#pragma pack()

#endif
